### ISSUE TITLE
How about a docker image with a headless server?

### ISSUE THREAD

**Issue by zcube** [maxsupermanhd/FactoCord-3.0#48]
I think it will be more convenient to use if it is packaged and distributed with Docker.

https://github.com/ZCube/FactoCord-3.0/commit/eeda51aacb3a1b46b655ba264807eb59da1601ad

```yaml
version: '3.5'

services:
  factorio:
    image: ghcr.io/zcube/factocord-3.0:feature-docker
    restart: unless-stopped
    ports:
     - "${PORT:-34197}:${PORT:-34197}/udp"
     - "27015:27015/tcp"
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ./factorio:/factorio
    environment:
      - PORT=${PORT:-34197}
      - TZ=UTC
      - DISCORD_TOKEN=secret_token
      - FACTORIO_CHANNEL_ID=id
```
